---
title: "Movie Statistics Dashboard \n Prem Chandra Skehar Reddy Mettupalli \n 08262627"
output: pdf_document
date: "2024-04-08"
---

# Movies Statistics - An Interactive Dashboard:

# **Introduction:**

When ever we watch a nice movie we might sometimes think about the different factors that made it successful. Movie analysis has become an important aspect of film making. Directors, Writers, Producers, and distributors will be often trying to make movies which they want be accepted by all kinds of people around the world and they also want those movies to be profitable.

Analyzing top movies which have performed well at boxofiice and also which were accepted by wide range of people help filmmakers to decide on what kind of films they need to make or it will at least help them in making a good movie. This also helps viewers to pick movies to watch with out wasting much time on selecting what to watch.

The performance of a movie depends upon several factors such as Budget spent on it, Genre of the movie, directors, actors and etc. Analyzing these factors helps filmmakers to decide on which things they need to invest their talent, time, and money.

# **Data set:**

The data set contains a list of IMDB top 50 rated movies and details of those movies like the director of the movie, budget of the movie, gross earnings, profit, genre, year in which the movie was released run time and etc.

Different fields of the data:

-   S.no: An unique number given to represent each movie.

-   Title: Title of the movie.

-   Run-time: Total Duration of the movie in minutes.

-   Genre: Genre of the movie.

-   Rating: Average Rating of the movie (on a scale of 0-10).

-   Votes: Total numbers of votes received by the movie.

-   Gross_Earning_in_Mil: Gross earnings of the movie in million.

-   Director: Name of the Director.

-   Actor: Lead actor in the movie.

-   Year: Year in which the movie was released.

-   Budget_in_Million: Overall Budget spent on a movie in millions.

-   Profit_in_Mil: Total profit of made by the movie in millions.

# **Purpose:**

A web based interactive dashboard was created to visualize the data related to the top 20 movies among the 50 movies that we have in our data set using R shiny.

Our data set contains a list of IMDB top 50 rated movies and details of those movies like the director of the movie, budget of the movie, gross earnings, profit, genre, year in which the movie was released run time and etc. A web based interactive dashboard was created to visualize this data using R shiny

This interactive visual dashboard helps in analyzing the trend of top 20 movies from the 50 that we have collected, which are being liked by wide range and verity of people. This dashboard also helps in finding out the insights which made the films this popular so that investors and directors can focus on them while making a movie. Viewers can also interact with the dash board to find out more things about the movies they liked and can use them to search similar kind of movies to watch, if they like a top movie they can find out its genre and the director who directed it and can search for some similar films which have these things in common.

This dashboard visualizes the movie data using plots like bar-charts, pie-charts, Tables, and scatter-plots these plots and tables will be interactive and they also have filtering options such that you can only look at what you want.

# **Problems addressed and related previous studies:**

This Dashboard helps in comparing *top 20* movies across different categories like ratings, Gross Earnings, Number of votes, Genre and etc all together in one place which will give some useful insights to the users.

*"Over the past twenty years, people have seen considerable growth in film industry. There are two common measurements for movie quality, financial metric of net profit and reception metric in the form of ratings assigned by moviegoers on websites."[1].*

Our dashboard helps in comparing different aspects of a movie based on its budget, votes, ratings, directors, and the genre .Comparative and predictive analysis helps in finding associations and relation between different variables which is an impact full thing to do in analyzing the future performance of anything like a business or film making or in health industry.

*"Leveraging historical data from the movie industry, this study built a predictive model for movie success, deviating from past studies by predicting profit (as opposed to revenue) at early stages of production (as opposed to just prior to release) to increase investor certainty." [2]*

Estimating the factors that are leading to the success of a movie is an important aspect to analyse for an investors. Investing huge amount on a movie is often considered risky as there are several factors like Genre, Actors and Directors involved in the success of a movie, analyzing or going through these factors helps in predicting the success of a movie which benefits the investors.

*"However, from an investor’s standpoint, one would want to be as assured as possible that his/her investment will ultimately lead to returns or profits."[2]*

Budget is an important aspect that majorly contributes to the profits that can be made by a movie our dashboard shows there is a positive correlation between the budget spent on a movie and the profits earned by the movie.

*"Two variable the budget and release date are in a significant positive correlation with box office revenue, the other ten determinants found to be insignificant."[3]*

\newpage

# Components of the Dashboard:

The dashboard contains different tabs with plots and tables:

1.  Plots Tab

2.  Top Movies by gross earnings Tab

3.  Summary tab

**Plots Tab:**

The Dashboard contains 4 plots in total.

-   ***Top Movies by total votes :*** this bar chart Shows the top 20 movies based on the total votes they have received. Looking at the plot we can say that The shawshank redemption stands in the top when it comes to the overall ratings received and The Prestige stands last.

-   ***Top Directors by total votes:*** This bar chart shows the top 20 Directors based on the total number of votes they have received for all the movies in the top 20 that are made by them. From the bar plot we can say that Christopher Nolan is the most rated (Highest number of votes) director in the top 20 movies list.

-   ***Proportions of different Genres:*** The pie chart displays the proportions of each genre that are related to the top 20 movies. The pie chart depicts that Crime and Drama constitutes to the majority of the proportion where as mystery, western, horror, and comedy are the least interested genres***.***

-   ***Relation between Budget and Profit:*** The correlation plot depicts about the relation between the budget spent on a movie in millions and the profit gained by the movie in millions. User can interact with the plot. As indicated by the blue linear relation trend line our correlation plot shows a positive relationship or association between the variables budget and profit. We can not say that budget alone is associated with profits of a movie there are many other factors that contributes to the success of a movie.

**Top Movies by gross earnings Tab:**

This tab contains a table which is used to display the top 20 movies based on their gross earnings. It has four different columns namely Title, Director, Gross_Earnings_in_mil, Genre. This table helps in comparing the gross earnings of a movie with its genre and also gives the director name.

**Summary Tab:**

Summary table in this tab display the summary of all the fields related to the top 20 movies. This table displays information of averages, median, mode, minimum and maximum values of the corresponding fields.

# **Instructions for using the Dashboard:**

-   Access the app by clicking on the link provide ([Movie Statistics dashboard](https://premmettupalli.shinyapps.io/Top50-Movie-Analysis/)). This link will take you to web page of the dash board.

-   By default there wont be any filters selected from the sidebar panel and you be looking at the plots tab

-   The plots tab contains 4 different plots and you can interact with all the plots by hovering on the different sections or points or bars of the plots. Each plot has its own purpose, Bar plots shows the popularity of the movies and directors based on the overall votes they received, correlation plot depicts about relation between aspects like budget and profit and also the proportion of genres is shown by using a pie chart

-   By clicking on the second tab ( Top Movies By Gross Earnings Tab) you will be navigated to the page where you will have a table that contains the list of the top 20 movies which are ordered based on their Gross earnings. You have a Search bar in the top right of the table which helps you to search for the gross earnings of different movies using the title of the movie or the name of the director. You can click on the drop down menu on the top left to select the number of rows you want to display in a single page.

-   Clicking on the third tab you get to see a summary section where you can find the mean, median, average, maximum, and minimum values for the data that you are analyzing.

-   The Sidebar panel consists of filters which can be commonly used across all the three different tabs that are present

    **Using the Filters:**

    Side bar panel contains different filtering options which are stated below:

    -   ***Filter by Genre:*** This filter includes options for selecting all the different genres of the top 20 movies. It helps the users to choose a specific genre they are interested in by selecting them from the drop-down menu.

    -   ***Filter by Year:*** This is a range selector type of filter. By using the slider users can choose the range of the years which helps to filter the data based on the release year of the movie.

    -   ***Filter by Rating:*** This is an another range selector type of filter with which user can select the range of ratings to filter the movies data based on the overall ratings they have received. It ranges from the maximum rating to the minimum rating values that are present in the top 20.

    -   ***Filter by Director:*** This is a drop down filter with which an user can select the director of their interest to display the statistics of the movies that are associated to that particular director. This filter has a drop down menu which includes options for selecting all the different directors of the top 20 movie.

# **Conclusion**

The Interactive Movie Statistics Analysis Application provides users with a powerful tool for analyzing and exploring movie data. By addressing the problems of limited data visualization tools, complex data analysis processes, and limited access to movie data, the application aims to empower users to make informed decisions and gain valuable insights into the movie industry.

# References:

1.  [Zheng Gao](https://link.springer.com/chapter/10.1007/978-3-030-15742-5_63#auth-Zheng-Gao), [Vincent Malic](https://link.springer.com/chapter/10.1007/978-3-030-15742-5_63#auth-Vincent-Malic), [Shutian Ma](https://link.springer.com/chapter/10.1007/978-3-030-15742-5_63#auth-Shutian-Ma) [Patrick Shih](https://link.springer.com/chapter/10.1007/978-3-030-15742-5_63#auth-Patrick-Shih) : **How to Make a Successful Movie: Factor Analysis from both Financial and Critical Perspectives :** <https://link.springer.com/chapter/10.1007/978-3-030-15742-5_63#auth-Vincent-Malic>.

2.  [Michael Lash](https://link.springer.com/chapter/10.1007/978-3-319-16268-3_41#auth-Michael-Lash), [Sunyang Fu](https://link.springer.com/chapter/10.1007/978-3-319-16268-3_41#auth-Sunyang-Fu), [Shiyao Wang](https://link.springer.com/chapter/10.1007/978-3-319-16268-3_41#auth-Shiyao-Wang), [Kang Zhao](https://link.springer.com/chapter/10.1007/978-3-319-16268-3_41#auth-Kang-Zhao) : **Early Prediction of Movie Success — What, Who, and When :** <https://arxiv.org/abs/1506.05382>.

3.  Yasemin Bozdogan: The determinants of box office revenue: a case based study: thirty, low budget, highest ROI films vs. thirty, big budget, highest grossing Hollywood films. Economics and Finance. 2013. ffdumas-00909948f :<https://dumas.ccsd.cnrs.fr/dumas-00909948/document>.

4.  Rshinny

5.  plotty

6.  
